language: python
matrix:
  include:
   - env: TOXENV=py27-dj18
     python: 2.7
   - env: TOXENV=pypy-dj18
     python: pypy
   - env: TOXENV=py34-dj18
     python: 3.4
   - env: TOXENV=py35-dj18
     python: 3.5
   - env: TOXENV=py36-dj18
     python: 3.6
   - env: TOXENV=py27-dj19
     python: 2.7
   - env: TOXENV=pypy-dj19
     python: pypy
   - env: TOXENV=py34-dj19
     python: 3.4
   - env: TOXENV=py35-dj19
     python: 3.5
   - env: TOXENV=py36-dj19
     python: 3.6
   - env: TOXENV=py27-dj110
     python: 2.7
   - env: TOXENV=pypy-dj110
     python: pypy
   - env: TOXENV=py34-dj110
     python: 3.4
   - env: TOXENV=py35-dj110
     python: 3.5
   - env: TOXENV=py36-dj110
     python: 3.6
   - env: TOXENV=py27-dj111
     python: 2.7
   - env: TOXENV=pypy-dj111
     python: pypy
   - env: TOXENV=py34-dj111
     python: 3.4
   - env: TOXENV=py35-dj111
     python: 3.5
   - env: TOXENV=py36-dj111
     python: 3.6
   - env: TOXENV=flake8
     python: 3.5
install:
  - pip install tox
script:
  - tox
